name: user_defaults
description: Flutter plugin for reading and writing simple key-value pairs.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
